title:            Nicolas Risberg Online Portfolio
subtitle:		  Rendering | UI | Audio 
description:      Online Portfolio showcasing schoolwork done at The Game Assembly in Stockholm, 2021 as well as my CV and other cool things.
copyright:        Nicolas Risberg
url: # add your custom site url (format: https://example.com)


future:      false  # publish future dated posts --  true, false (default)
highlighter: rouge
# markdown:    kramdown
# gems:
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jekyll-gist
#   - jekyll-feed

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:year-:month-:day/:title.html

# Amount of post to show on home page
paginate: 5

#kramdown:
#  input: GFM
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  enable_coderay: false

include:
  - .htaccess

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
