title:            Nicolas Risberg Online Portfolio
subtitle:		  Rendering | UI | Audio 
description:      Online Portfolio showcasing schoolwork done at The Game Assembly in Stockholm, 2021 as well as my CV and other cool things.
copyright:        Nicolas Risberg
url: # add your custom site url (format: https://example.com)


future:      false  # publish future dated posts --  true, false (default)
highlighter: rouge
# markdown:    kramdown
# gems:
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jekyll-gist
#   - jekyll-feed

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate-v2
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate-v2
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: compressed

# permalink: /:categories/:year-:month-:day/:title.html
permalink: /:year-:month-:day/:title.html

# Amount of post to show on home page
# paginate: 5

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  #permalink: '/page/:num.md'
  #permalink: /:category/:year/:month/:title.html

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ' - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################

#### AUTO PAGES #####
autopages:
  enabled: true

  categories:
    layouts:
      - 'autopage_category.html'
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    slugify:
      mode: 'default'
      case: false

  collections:
    layouts:  
      - 'autopage_collection.html'
    title: 'Posts in collection :coll'
    permalink: '/collection/:coll'
    slugify:
      mode: 'default'
      case: false

  tags:
    layouts:
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag'
    permalink: '/tag/:tag'
    slugify:
      mode: 'default'
      case: false

 #### AUTO PAGES ####

#kramdown:
#  input: GFM
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  enable_coderay: false

include:
  - .htaccess

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - /docs/
